@echo off
echo Starting Credit Card Agent on PORT 8001...
echo Opening Browser...
start http://localhost:8001
echo Starting Server...
venv\Scripts\python -m uvicorn backend.main:app --host 0.0.0.0 --port 8001
pause
